### ISSUE TITLE
Friends: front end

### ISSUE THREAD

**Issue by PeterPea** [Heath-Mayocchi/Capstone-2017#107]
As a user I want to view and manage my list of friends so that I can
a) view messages only from selected friends and
c) add and remove contacts from my list of friends

Acceptance Criteria:
Feed Carousel can show posts from selected users only 
A button can remove a contact from friends list
A button can add contact to friends list
A textbox which searches through contacts

**Comment by DaveMack** [comment]
Changes to the feed carousel would need to be made in the feed page, and shouldn't be part of this task.  The rest is ready to start testing.  I haven't done anything about blocking users yet.
