### ISSUE TITLE
Create user stories for Add Friends back end

### ISSUE THREAD

**Issue by Heath-Mayocchi** [Heath-Mayocchi/Capstone-2017#159]
tasks and acceptance criteria for all back end elements

**Comment by DaveMack** [comment]
As a user I want to be able to see all of my frineds in one list so I can browse through them.

As a user I want to be able to remove people from my friends list so I can avoid seeing their posts.

As a user I want to be able to see a list of people who aren't my friends yet, so I can decide who to add.

As a user I want to be able to add people to my friends.

As a user I want to be able to view posts just from my friends.

As a user I want to be able to block the posts of certain people from appearing in my feed, so I can ignore them.

As a user I want to be able to see a list of people I have blocked

As a user I want to be able to remove people from the list of blocked users.

**Comment by Heath-Mayocchi** [comment]
I guess don't bother with creating these now, I'll just create new issues for the 
- remove friends button
- changing the add friends button text
- add friends button
