### ISSUE TITLE
Navigation buttons

### ISSUE THREAD

**Issue by Heath-Mayocchi** [Heath-Mayocchi/Capstone-2017#66]
Create navigation buttons (Back, Next, Previous, React) using HTML, CSS and JavaScript
able to navigate focus for other page elements and then switch to prev, next for the feed

**Comment by PeterPea** [comment]
I noticed that if you click off the buttons it loses focus and the navigation no longer works until you click on a button. Whilst this doesn't matter if only the navigation buttons are being used it may be an issue if a teacher accidentally clicks off.

**Comment by Heath-Mayocchi** [comment]
I don't see anyway around this because it needs to be operational by both mouse and keyboard. But they can either refresh the page or like you say, click on one of the footer nav buttons to resume normal functionality. If you have any ideas on how we can make it better then please let us know, otherwise it is an issue we can't spend more time on. We can't spend too much time on singular issues, and we have gone over on this one already.
