### ISSUE TITLE
 Admin user management: friends list frontend

### ISSUE THREAD

**Issue by PeterPea** [Heath-Mayocchi/Capstone-2017#96]
Admin can add friends from the user management screen

Acceptance Criteria:
A list with checkboxes for current friends
a button to remove user/s from the list
a button to add a friend, this will open the add friend screen

**Comment by Heath-Mayocchi** [comment]
box needs to be smaller, padding between the main box and the check boxes is too large
box expands too much on a larger screen, width should be set pixels

**Comment by Heath-Mayocchi** [comment]
fix display issues
